---
name: build

on:
  push:
  pull_request:
  repository_dispatch:
    types:
      - apb
  workflow_dispatch:
    inputs:
      debug-workflow:
        description: Debug the workflow with a remote shell
        required: false
        default: "false"

jobs:
  lint:
    permissions:
      # actions/checkout needs this to fetch the repository
      contents: read
    uses: cisagov/github-actions-workflows/.github/workflows/common-lint.yml@first-commits
    with:
      # Cast to boolean
      run-tmate: ${{ github.event.inputs.debug-workflow == 'true' }}
